### ISSUE TITLE
How to distinguish a BananaPi from a Cubietruck?

### ISSUE THREAD

**Issue by gkoala** [wiringX/wiringX#1]
Both boards feature an A20 SOC and the current identification code in WiringX/bananapi.c only checks for that. But is there even a reasonable way of distinguishing those boards?

Unfortunately, it is necessary to separate them because of incompatible GPIO numbering, ...

**Comment by CurlyMoo** [comment]
What is the output of cpuinfo in the Cubieboard?

**Comment by CurlyMoo** [comment]
I've got another idea. Can you post the mac address of the LAN interface of the Cubie? To get it to work, either the BananaPi or the Cubietruck needs to have a fixed mac address.

**Comment by linux4kix** [comment]
Sorry to be late to the party.  We should be able to use
/sys/devices/soc0/machine to distinguish boards using the same SOC.

**Comment by CurlyMoo** [comment]
Doesn't seem present on the Raspberry Pi and Radxa Rock (Pro).

**Comment by linux4kix** [comment]
Do they not use device-tree yet?

**Comment by CurlyMoo** [comment]
No

**Comment by gkoala** [comment]
Will try to answer those questions tonight as soon as I get to my cubie.

MAC address might be an idea, if there is a common board specific part for all cubies which differs from the bananas. Difficult to determine without documentation and access to a sufficient number of boards, though.

**Comment by gkoala** [comment]
### cat /proc/cpuinfo

Processor       : ARMv7 Processor rev 4 (v7l)
processor       : 0
BogoMIPS        : 956.47

processor       : 1
BogoMIPS        : 832.55

Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 4

Hardware        : sun7i
Revision        : 0000
Serial          : 0000000000000000
Chipid          : 16516649-80485471-52564848-08c0b591

### ifconfig

**eth0**      Link encap:Ethernet  HWaddr **`02:49:08:c0:b5:91`**
...

**wlan0**     Link encap:Ethernet  HWaddr **`98:3b:16:de:c7:c6`**
...

### Device tree

**/sys/devices/soc0** doesn't exist

**Comment by CurlyMoo** [comment]
Can you please use markup codes for better readability?

**Comment by Tony-HIT** [comment]
The mac address now is Banana Pro/Pi and Cubieboard are all fixed according to the cpu serial number. If we want to distinguish the Banana Pro/Pi and Cubieboard, we need to fix the mac address.
And I also have an idea that we can use different machine id in kernel, but this need user to use the special kernel.

**Comment by CurlyMoo** [comment]
If all current doesn't work, then the only way would be to ask for user input. Let the set the device somewhere so the program knows.

**Comment by smutbert** [comment]
Afaik the Banana Pi doesn't have a S/PDIF output. So i would suspect the device sunxisndspdif will only appear on the Cubietruck.

``` shell
$ cat /proc/asound/cards
 0 [sunxicodec     ]: sunxi-CODEC - sunxi-CODEC
                      sunxi-CODEC  Audio Codec
 1 [sunxisndspdif  ]: sunxi-sndspdif - sunxi-sndspdif
                      sunxi-sndspdif
 2 [sunxisndi2s    ]: sunxi-sndi2s - sunxi-sndi2s
                      sunxi-sndi2s
```

i don't know if this is a good idea though...

**Comment by vitalogy** [comment]
Are there any news to get this work on a CubieTruck?
Running here a CubieTruck with Arch Linux on kernel-4.2-rc5 as a little server.
So i would also like to run pilight on this device, and pilight uses wiringX, but at this time there is no support for CubieTruck (CubieBoard3) in wiringX.

Could the following help to identify the device?

```
# cat /sys/firmware/devicetree/base/model
Cubietech Cubietruck
```

Kernel-4.2-rc5 uses a devicetree.

**Comment by smutbert** [comment]
most users will still run kernel 3.4.x I think. At least I do since the s/pdif-jack was my reason for choosing the cubietruck and sound was not (yet?) supported with more recent kernel versions last time I checked.

Of course it would be great if wiringX supported the cubietruck. gkoala, who started this issue, already did a great job porting wiringPi/wiringCB to the cubietruck. He posted his work in the german cubieboard-forum:
http://www.forum-cubieboard.de/Thread-wiringcb-wiringpi-und-cubietruck
in this post you find the link to the last version he posted
http://www.forum-cubieboard.de/Thread-wiringcb-wiringpi-und-cubietruck?pid=4399#pid4399

I had a few problems instaling it (i don't have sudo installed and had to do it manually) and in some situations you have to set up a pull-up to get a pull-down and vice versa, but apart from that everything worked fine.
I don't know pilight though and have no idea if it will work too.

**Comment by CurlyMoo** [comment]
People should just port directly into wiringX so we have one single library instead of all those individual wiringPi ports.

**Comment by RamiKhawaly** [comment]
_You are right_
_I'm using wiringPi and waiting for Pi4J (or other project) to support
wiringX to move. *
*i hope it will be soon_

**Comment by vitalogy** [comment]
I think with linux-3.4.x you can not clearly determine which board the user is running.
The only thing you can do is a process of elimination, like it is done [here](https://github.com/igorpecovnik/lib/blob/next/scripts/armhwinfo)
With this old kernel you get only a generic description which SoC (sun4i, sun7i, ... ) is used.

For the cubietruck you could check for the totalmem of 2GB. But i don't know if there are other sun7i boards around with a ram of 2GB.

The better solution is to use the description from the devicetree from a newer kernel.
You get an unique string by checking

```
cat /sys/firmware/devicetree/base/model
```

or by

```
dmesg |grep "Machine model"
```

I have also take look in bananapi.c, why it checks for sun4i and sun7i?
Afaik BananaPi and BananaPro (if it cheks for that at all) are using A20 SoC (sun7i), only the popular Cubieboard has an A10 SoC (sun4i)!

| Board | SoC | RAM | Pins |
| --- | --- | --- | --- |
| Cubieboard | A10 sun4i | 1GB | 96 external pins |
| Cubieboard2 | A20 sun7i | 1GB | 96 external pins |
| Cubietruck | A20 sun7i | 2GB | 54 external pins |
| Banana Pi | A20 sun7i | 1GB | 26 external pins |
| Banana Pro | A20 sun7i | 1GB | 40 external pins |

> He posted his work in the german cubieboard-forum:
> http://www.forum-cubieboard.de/Thread-wiringcb-wiringpi-und-cubietruck
> in this post you find the link to the last version he posted
> http://www.forum-cubieboard.de/Thread-wiringcb-wiringpi-und-cubietruck?pid=4399#pid4399

I have seen this, but his port will propably not work with pilight.

**Comment by CurlyMoo** [comment]
New rewrite branch has the auto detection removed. Users much tell wiringX what platform they use.
