### ISSUE TITLE
error while compiling with "libi2c-dev" installed

### ISSUE THREAD

**Issue by GreenMarc** [wiringX/wiringX#101]
Hi,
on my RaspberryPi 2/Raspbian it wont compile while libi2c-dev is installed :

> pi@raspberrypi /opt/wiringX-wiringX-196f892 $ mkdir build
pi@raspberrypi /opt/wiringX-wiringX-196f892 $ cd build
pi@raspberrypi /opt/wiringX-wiringX-196f892/build $ cmake ..
-- The C compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/wiringX-wiringX-196f892/build
pi@raspberrypi /opt/wiringX-wiringX-196f892/build $ make
Scanning dependencies of target sources
[  6%] Building C object CMakeFiles/sources.dir/src/bananapi.c.o
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:19:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c-dev.h:37:8: error: redefinition of 'struct i2c_msg'
 struct i2c_msg {
        ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:18:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c.h:68:8: note: originally defined here
 struct i2c_msg {
        ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:19:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c-dev.h:89:7: error: redefinition of 'union i2c_smbus_data'
 union i2c_smbus_data {
       ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:18:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c.h:128:7: note: originally defined here
 union i2c_smbus_data {
       ^
In file included from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:0:
/opt/wiringX-wiringX-196f892/src/i2c-dev.h:22:14: error: conflicting types for 'i2c_smbus_access'
 INLINE __s32 i2c_smbus_access(int fd, char rw, int cmd, int size, union i2c_smbus_data *data) __attribute__((always_inline));
              ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:19:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c-dev.h:156:21: note: previous definition of 'i2c_smbus_access' was here
 static inline __s32 i2c_smbus_access(int file, char read_write, __u8 command,
                     ^
In file included from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:0:
/opt/wiringX-wiringX-196f892/src/i2c-dev.h:24:14: error: conflicting types for 'i2c_smbus_write_byte'
 INLINE __s32 i2c_smbus_write_byte(int fd, int value) __attribute__((always_inline));
              ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:19:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c-dev.h:183:21: note: previous definition of 'i2c_smbus_write_byte' was here
 static inline __s32 i2c_smbus_write_byte(int file, __u8 value)
                     ^
In file included from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:0:
/opt/wiringX-wiringX-196f892/src/i2c-dev.h:25:14: error: conflicting types for 'i2c_smbus_read_byte_data'
 INLINE __s32 i2c_smbus_read_byte_data(int fd, int cmd) __attribute__((always_inline));
              ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:19:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c-dev.h:189:21: note: previous definition of 'i2c_smbus_read_byte_data' was here
 static inline __s32 i2c_smbus_read_byte_data(int file, __u8 command)
                     ^
In file included from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:0:
/opt/wiringX-wiringX-196f892/src/i2c-dev.h:26:14: error: conflicting types for 'i2c_smbus_write_byte_data'
 INLINE __s32 i2c_smbus_write_byte_data(int fd, int cmd, int value) __attribute__((always_inline));
              ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:19:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c-dev.h:199:21: note: previous definition of 'i2c_smbus_write_byte_data' was here
 static inline __s32 i2c_smbus_write_byte_data(int file, __u8 command,
                     ^
In file included from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:0:
/opt/wiringX-wiringX-196f892/src/i2c-dev.h:27:14: error: conflicting types for 'i2c_smbus_read_word_data'
 INLINE __s32 i2c_smbus_read_word_data(int fd, int cmd) __attribute__((always_inline));
              ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:19:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c-dev.h:208:21: note: previous definition of 'i2c_smbus_read_word_data' was here
 static inline __s32 i2c_smbus_read_word_data(int file, __u8 command)
                     ^
In file included from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:0:
/opt/wiringX-wiringX-196f892/src/i2c-dev.h:28:14: error: conflicting types for 'i2c_smbus_write_word_data'
 INLINE __s32 i2c_smbus_write_word_data(int fd, int cmd, __u16 value) __attribute__((always_inline));
              ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:19:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c-dev.h:218:21: note: previous definition of 'i2c_smbus_write_word_data' was here
 static inline __s32 i2c_smbus_write_word_data(int file, __u8 command,
                     ^
In file included from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:0:
/opt/wiringX-wiringX-196f892/src/i2c-dev.h:40:14: error: redefinition of 'i2c_smbus_read_byte'
 INLINE __s32 i2c_smbus_read_byte(int fd) {
              ^
In file included from /opt/wiringX-wiringX-196f892/src/i2c-dev.h:19:0,
                 from /opt/wiringX-wiringX-196f892/src/bananapi.c:30:
/usr/include/linux/i2c-dev.h:174:21: note: previous definition of 'i2c_smbus_read_byte' was here
 static inline __s32 i2c_smbus_read_byte(int file)
                     ^
CMakeFiles/sources.dir/build.make:61: recipe for target 'CMakeFiles/sources.dir/src/bananapi.c.o' failed
make[2]: *** [CMakeFiles/sources.dir/src/bananapi.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/sources.dir/all' failed
make[1]: *** [CMakeFiles/sources.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi /opt/wiringX-wiringX-196f892/build $ >

if i uninstall "libi2c-dev" it compiles without problems...;

> pi@raspberrypi /opt/wiringX-wiringX-196f892/build $ make
[  6%] Building C object CMakeFiles/sources.dir/src/bananapi.c.o
[ 12%] Building C object CMakeFiles/sources.dir/src/ci20.c.o
[ 18%] Building C object CMakeFiles/sources.dir/src/hummingboard.c.o
[ 25%] Building C object CMakeFiles/sources.dir/src/radxa.c.o
[ 31%] Building C object CMakeFiles/sources.dir/src/raspberrypi.c.o
[ 37%] Building C object CMakeFiles/sources.dir/src/wiringX.c.o
[ 37%] Built target sources
Scanning dependencies of target wiringx_static
[ 43%] Linking C static library libwiringX.a
[ 43%] Built target wiringx_static
Scanning dependencies of target wiringx_shared
[ 50%] Linking C shared library libwiringX.so
[ 50%] Built target wiringx_shared
Scanning dependencies of target wiringx-blink
[ 56%] Building C object CMakeFiles/wiringx-blink.dir/examples/blink.c.o
[ 62%] Linking C executable wiringx-blink
[ 62%] Built target wiringx-blink
Scanning dependencies of target wiringx-interrupt
[ 68%] Building C object CMakeFiles/wiringx-interrupt.dir/examples/interrupt.c.o
[ 75%] Linking C executable wiringx-interrupt
[ 75%] Built target wiringx-interrupt
Scanning dependencies of target wiringx-read
[ 81%] Building C object CMakeFiles/wiringx-read.dir/examples/read.c.o
[ 87%] Linking C executable wiringx-read
[ 87%] Built target wiringx-read
Scanning dependencies of target wiringx-i2c-spi
[ 93%] Building C object CMakeFiles/wiringx-i2c-spi.dir/examples/i2c_spi.c.o
[100%] Linking C executable wiringx-i2c-spi
[100%] Built target wiringx-i2c-spi
pi@raspberrypi /opt/wiringX-wiringX-196f892/build $
>

Its not realy a problem, only a note for other users with the same error.....

Greetz 
Marc

**Comment by CurlyMoo** [comment]
Thanks for reporting, but not necessary to keep it open.
