### ISSUE TITLE
General questions regarding the wiringX

### ISSUE THREAD

**Issue by DRSDavidSoft** [wiringX/wiringX#102]
Hi there

I've just discovered `wiringX`, and to me it's a great project because I can finally use the same `wiring` interface on my Pi boards. Nice job on making it modular, and rewriting it! :D

However, I have some questions/concerns regarding its development:

1. How does it stack up against other libraries such as `WiringOtherPi`?
https://github.com/lanefu/WiringOtherPi

2. How many devs are currently working on `wiringX`? Is this project actively maintained?

3. If a manufacturer (or a community member) decides to write a port for another SoC, Is there a `Getting Started` page to instruct on how to write the port? If not, could you make one?

4. And last but not least, how is this project going to be kept updated with the original `wiringPi`? More importantly, is there any plans for it?

Also, do you plan to support bridges like what `wiringPi-NodeJs` and `wiringPi-PHP` do?

I appreciate the work you do and your time

**Comment by CurlyMoo** [comment]
> How does it stack up against other libraries such as WiringOtherPi?

Don't know. Until now i or companies wrote code directly for wiringX.

> How many devs are currently working on wiringX? Is this project actively maintained?

I and some manufacturers when needed. What's supported just works.

> If a manufacturer (or a community member) decides to write a port for another SoC, Is there a Getting Started page to instruct on how to write the port? If not, could you make one?

If you have questions just ask, but i believe it's pretty self explanatory

> And last but not least, how is this project going to be kept updated with the original wiringPi? More importantly, is there any plans for it?

Not at all.

> Also, do you plan to support bridges like what wiringPi-NodeJs and wiringPi-PHP do?

Nope
