### ISSUE TITLE
Logo Design for WiringX

### ISSUE THREAD

**Issue by DRSDavidSoft** [wiringX/wiringX#103]
Hi again

### I decided to design a logo for the `wiringX` project, considering that the GitHub page had none.

<img src="https://user-images.githubusercontent.com/4673812/33490803-83cf491c-d6cd-11e7-8823-20d67bbc646c.png" width="256px" />

### And a minimal design:

<img src="https://user-images.githubusercontent.com/4673812/33490824-93ba6f8c-d6cd-11e7-959c-9dc009b66169.png" width="128px"/>

<hr>

### What do you think? Is it good enough to be used here?

<img width="256px" alt="prev_demop" src="https://user-images.githubusercontent.com/4673812/33491034-45311996-d6ce-11e7-9847-d64ee2067139.png">

**Comment by pilino1234** [comment]
I like it, 👍 from me!

**Comment by CurlyMoo** [comment]
Great that you are willing to put your time into making a logo! But to be honest, it reminds me of:
`¯\_(ツ)_/¯`

I don't think that covers wiringX :smile:
