### ISSUE TITLE
undefined symbol: orangepipc2Init when use python lib

### ISSUE THREAD

**Issue by kostyanab** [wiringX/wiringX#104]
On Arch Linux ARM, i install "python-wiringx-git" pkg. I use hummingboard pro with dual imx6 som. After that i try run command:
`python -c "from wiringX import gpio"`
I have an error:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib/python3.6/site-packages/wiringX/gpio.cpython-36m-arm-linux-gnueabihf.so: undefined symbol: orangepipc2Init`
Thanks for help and sorry for my bed english.

**Comment by CurlyMoo** [comment]
Fixed
