### ISSUE TITLE
Raspberry pi 3b+ support

### ISSUE THREAD

**Issue by louis-lau** [wiringX/wiringX#105]
I just switched from a 1b+ to a 3b+. Pilight has stopped working and there's absolutely no errors. Using gpio-platform raspberrypi3.

Is the 3b+ not supported yet? or am I going crazy?

Thanks

**Comment by CurlyMoo** [comment]
Is that the latest Raspberry Pi?

**Comment by louis-lau** [comment]
Yup, released a couple of weeks ago :)
https://www.raspberrypi.org/products/raspberry-pi-3-model-b-plus/

Pinout is exactly the same as the 3b. It also uses the same processor at a higher clockspeed.

**Comment by CurlyMoo** [comment]
Can you use the platform 'raspberrypi3' and check if that works?

**Comment by louis-lau** [comment]
Did that, it didn't.

**Comment by CurlyMoo** [comment]
Can you eloborate?

**Comment by louis-lau** [comment]
Sure, this is the pilight config I'm using:
```
{
        "devices": {},
        "rules": {},
        "gui": {},
        "settings": {
                "log-level": 6,
                "pid-file": "/var/run/pilight.pid",
                "log-file": "/var/log/pilight.log",
                "webserver-enable": 1,
                "webserver-root": "/usr/local/share/pilight/webgui",
                "webserver-http-port": 5001,
                "webserver-cache": 1,
                "gpio-platform": "raspberrypi3",
                "port": 5000
        },
        "hardware": {
                "433gpio": {
                        "sender": 0,
                        "receiver": 1
                }
        },
        "registry": {
                "webserver": {
                        "ssl": {
                                "certificate": {
                                        "secure": 0,
                                        "location": "/etc/pilight/pilight.pem"
                                }
                        }
                },
                "pilight": {
                        "version": {
                                "current": "8.0.10"
                        }
                }
        }
```

I have a RF thing connected to wiringpi gpio 0. When using the send command it looks successful (no errors), but nothing happens on my switches.

Then changed back the platform to raspberrypi1b+ and put it back into my old pi just to be sure. Using the exact same gpio pins it works fine.

**Comment by louis-lau** [comment]
Nothing in the logs btw, any debugging I can do?

**Comment by CurlyMoo** [comment]
Can you check using the wiringX examples?

**Comment by louis-lau** [comment]
Sure! on the 1b+:
```
pi@raspberrypi:~ $ sudo wiringx-blink raspberrypi1b+ 10
Writing to GPIO 10: High
Writing to GPIO 10: Low
Writing to GPIO 10: High
Writing to GPIO 10: Low
Writing to GPIO 10: High
Writing to GPIO 10: Low
Writing to GPIO 10: High
Writing to GPIO 10: Low
Writing to GPIO 10: High
Writing to GPIO 10: Low
^C
pi@raspberrypi:~ $
```

On the 3b+:
```
pi@raspberrypi:~ $ sudo wiringx-blink raspberrypi3 10
Writing to GPIO 10: High
Writing to GPIO 10: Low
Writing to GPIO 10: High
Writing to GPIO 10: Low
Writing to GPIO 10: High
Writing to GPIO 10: Low
Writing to GPIO 10: High
Writing to GPIO 10: Low
^C
pi@raspberrypi:~ $
```

So, nothing special it looks like

**Comment by louis-lau** [comment]
I don't think I have something to test the pin with though (except for the RF module)

**Comment by CurlyMoo** [comment]
Ofc, you need a LED or something to actually see if the GPIO works.

**Comment by louis-lau** [comment]
Heheh, thought so. I'll see if I can find something

**Comment by louis-lau** [comment]
Alright fuck. I ripped a led out of an old appliance, and it's working...

Any clues as to why the RF module isn't working with pilight?

**Comment by louis-lau** [comment]
(it's one of these)
![transmitter](http://img.dxcdn.com/productimages/sku_149254_1.jpg)

**Comment by louis-lau** [comment]
Well shit, looks like it was my power supply.
Thanks a lot for your time! (and sorry for wasting it)

At least now you know for sure it's compatible with the 3b+ 😄
