### ISSUE TITLE
python wrapper's "gpio.setup" api

### ISSUE THREAD

**Issue by ASI-Granby** [wiringX/wiringX#108]
In the “blink.py” example there’s a line that says “gpio.setup(gpio.RASPBERRYPI1B2)”. I assume this is where I enter the name of my board but I can’t figure out how. I have a hummingboard gate so looking at the manual I thought it might be “gpio.setup(gpio.hummingboard_gate_edge_dq)” or something to that effect but nothing seems to work, I get a no attribute error.

**Comment by CurlyMoo** [comment]
Here is your list:
https://github.com/wiringX/wiringX/blob/master/python/wiringX/wiringx.c#L391-L409

**Comment by ASI-Granby** [comment]
Thank you! I should have looked harder in the source.
