### ISSUE TITLE
python import error on Raspberry Pi 3B+: gpio.so: undefined symbol: broadcom2711Init

### ISSUE THREAD

**Issue by ZalerC** [wiringX/wiringX#111]
I get the following error when I attempt to do "from wiringX import gpio":
ImportError: /usr/lib/python3.8/site-packages/wiringX/gpio.cpython-38-aarch64-linux-gnu.so: undefined symbol: broadcom2711Init

I use the dist package or compile from git, all have this error.
How can I fix this error in Raspberry Pi 3B+.

**Comment by CurlyMoo** [comment]
Should be fixed.
