### ISSUE TITLE
wiringx.org domain gone?

### ISSUE THREAD

**Issue by felfert** [wiringX/wiringX#113]
I am trying to get some doc, but resolving the hosts in the links in README.md result in a NXDOMAIN response?!

**Comment by CurlyMoo** [comment]
They work fine here?

**Comment by felfert** [comment]
Not from Germany. Tested from 3 locations (on each, also a functional request for gmx.net):

1. On listserv.isdn4linux.de (dedicated server, hosted at IONOS (former 1&1)
```
[felfert@listserv ~]$ host -t ns wiringx.org
Host wiringx.org not found: 3(NXDOMAIN)
[felfert@listserv ~]$ host -t ns gmx.net
gmx.net name server ns-gmx.ui-dns.de.
gmx.net name server ns-gmx.ui-dns.com.
gmx.net name server ns-gmx.ui-dns.org.
gmx.net name server ns-gmx.ui-dns.biz.

```
2. On my home PC, connected via Vodafone cable
```
[felfert@fsun ~]$ host -t ns wiringx.org
Host wiringx.org not found: 3(NXDOMAIN)
[felfert@fsun ~]$ host -t ns gmx.net
gmx.net name server ns-gmx.ui-dns.biz.
gmx.net name server ns-gmx.ui-dns.com.
gmx.net name server ns-gmx.ui-dns.de.
gmx.net name server ns-gmx.ui-dns.org.
```
3. At work, connected via german Telekom
```
[felfert@jenkins ~]$ host -t ns wiringx.org
Host wiringx.org not found: 3(NXDOMAIN)
[felfert@jenkins ~]$ host -t ns gmx.net
gmx.net name server ns-gmx.ui-dns.com.
gmx.net name server ns-gmx.ui-dns.biz.
gmx.net name server ns-gmx.ui-dns.de.
gmx.net name server ns-gmx.ui-dns.org.

```

=> At least, DNS is down. Maybe you own that site (registered in NL) and have it's IP locally?

Reported down from US as well:
https://www.websiteplanet.com/webtools/down-or-not/?dorn=wiringx.org

**Comment by CurlyMoo** [comment]
Indeed: https://www.whatsmydns.net/#A/wiringx.org

**Comment by felfert** [comment]
Appears to work again :-)

**Comment by felfert** [comment]
Again: https://www.whatsmydns.net/#A/wiringx.org
