### ISSUE TITLE
Document requirements for adding platforms

### ISSUE THREAD

**Issue by crazystick** [wiringX/wiringX#16]
It would be nice to have a step-by-step guide for adding new platforms, to avoid breaking things:
- add implementation
  - minimum set of functions that must be supported (e.g. Init, GC, digitalRead, digitalWrite)
  - naming of functions
- changes to wiringX.c/h (need to #include platform.h)
- Python bindings
  - need to add platform.c in setup.py
- Documentation updates required

**Comment by CurlyMoo** [comment]
Are you willing to create that howto?

**Comment by crazystick** [comment]
I haven't added support for a new platform from scratch, so I'm probably not best suited to creating it, hint: @garysims has :-)

I'm of course willing to contribute to it

**Comment by CurlyMoo** [comment]
Can you check:
https://github.com/wiringX/wiringX/blob/master/CONTRIBUTING.md

**Comment by crazystick** [comment]
I think this is fine
