### ISSUE TITLE
GPIO numbering in sysfs is user definable on Cubieboards

### ISSUE THREAD

**Issue by gkoala** [wiringX/wiringX#2]
The GPIO numbers on the Cubie are user definable. I.e. if you find a GPIO in /sys/class/gpio/gpio# at all, and under which number you find a particular GPIO there is completely up to the user. There is no default.

As opposed to the other boards, the Cubie exposes this setup to the user via the FEX mechanism.

Since the only apparent way to set up interrupts is through sysfs ("poll" requires a file handle), this is a problem. Any predefined assumption made by wiringX may conflict with the user's setup. Ultimately, it may be necessary to let users define the mapping between wiringX numbers and GPIO numbers.

**Comment by CurlyMoo** [comment]
Can you tell me more about that FEX mechanism?

**Comment by gkoala** [comment]
Here's all about that: [link to FEX guide](http://linux-sunxi.org/Fex_Guide)

The gpio_para section is where you set up the GPIO pins.

The line:
`gpio_pin_2 = port:PH20<1><default><default><0>`

means that A20 gpio PH20 (see A20 documentation) will be found at /sys/class/gpio/gpio2, and will be set up as output (mux-feature 1) with initial value of 0 during linux boot. The configuration can be overwritten at runtime, of course. But the number mapping to /sys/class/gpio can not be modified at run time.

GPIOs don't need to be set up by FEX. It's possible to configure them entirely by software. The only exception are interrupts. As I wrote above, use of interrupts does require /sys/class/gpio access and hence a corresponding setup via FEX.

**Comment by CurlyMoo** [comment]
So FEX is like a device tree. How can we override this at run-time?

If we can override the configuration at run-time, then we can also do that in wiringX itself. But it should be the kernel / firmware developers that should provide uniform support.

**Comment by gkoala** [comment]
You overwrite the pin setup by writing the proper values into the pin configuration registers. WiringX is doing that even on the Raspberry Pi already. For plain pin reading/writing, WiringX is not going through sysfs.

But, as I said: This does not apply to the interrupts. These need to go through sysfs, and where you find a GPIO in the sysfs can NOT be overridden at runtime. That needs to be set up in FEX at boot time.

To illustrate: Pilight reads the output of the 433Mhz receiver via interrupts on a GPIO input pin. On Cubie, you'd use pin PI14 for that, for instance. But interrupts require that pin to be visible in the sysfs, so I need to set it up in FEX, e.g.:

`gpio_pin_3 = port:PI14<0><default><default><default>`

Then, wiringX can use the interrupt on it's pin no. 3 by accessing /sys/class/gpio/gpio3/edge and /sys/class/gpio/gpio3/value, exactly in the same way as it does that on the Raspberry.

Without that line in the FEX, there will be no /sys/class/gpio/gpio3 available.

**Comment by CurlyMoo** [comment]
And there is no uniform global FEX file being used by all distro's? If not, then we have to create our own standard and assume kernel developers will adopt.

**Comment by gkoala** [comment]
No, that's the problem. There is no such standard. The distributions come pretty much empty with respect to GPIO.

**Comment by CurlyMoo** [comment]
Then that's their problem. We can't do much about it. We will create our own mapping and it's up to the users to opt for support @cubieboard.

**Comment by gkoala** [comment]
Yep, my thoughts exactly. It's mostly a matter of documentation. Users will need to be told how they need to set up their FEX, so pilight can work.

**Comment by CurlyMoo** [comment]
Think of something reasonable and just adapt the index.html here with the new information:
https://github.com/pilight/wiringX/blob/gh-pages/index.html

**Comment by CurlyMoo** [comment]
You can check the new rewrite branch. That should help you port the Cubieboard much more easily.
