### ISSUE TITLE
How to use hardware interrupt in wiringX?

### ISSUE THREAD

**Issue by ypflll** [wiringX/wiringX#23]
I want to use hardware interrupt on a radxa board. I read radxa.c in wiringX and find that in function "static int radxaISR(int pin, int mode)",  no user defined interrupt function be called.
However, in wiringPi  (see https://github.com/WiringPi/WiringPi/blob/master/wiringPi/wiringPi.c), the function is defined like this: int wiringPiISR (int pin, int mode, void (*function)(void))--see a pointer of user defined function is imported, and in complementation of this function, an interruptHandler is called by:
pthread_create (&threadId, NULL, interruptHandler, &pin).  
But in radxa.c, I didn't see anywhere calling the "interruptHandler".
So, I am a little confused that  where the user interrupt handling function  is called? And how does radxaISR calls the interruptHandler?

**Comment by CurlyMoo** [comment]
https://github.com/wiringX/wiringX/blob/master/examples/interrupt.c

**Comment by ypflll** [comment]
Seems that I should check the "examples" folder first.
A little curious why wiringX changes the way to call the interrupt and does not align with wiringPi?

**Comment by CurlyMoo** [comment]
Because i don't think a GPIO library should not force you into using a fixed threaded implementation. In my implementation you can choose yourself how you implementent the interrupt handler inside your threads.

**Comment by ypflll** [comment]
Hi, I met a problem when testing the ''interrupt" example on a Rock-pro board.
I input a PWM wave in the GPIO 1, and it output "timeout" all the time (with no intervals, and no other information) in the terminal. And I detect no PWM in port 0--it seems that the program is death cycling in "*interrupt" .
So what's the problem? Have you tested the example on Rock?

**Comment by CurlyMoo** [comment]
The radxa doesn't support interrupt edge BOTH.

**Comment by ypflll** [comment]
Hi, I've solved my problem:
That's because for Radxa, a OS with kernal vision of 3.0.36 has a pin_base of 160, but wiringX does's considerates this. (Also, 3.0.36 doesn't support edge BOTH). I have fixed this bug.
For kernal vision 3.18.0, its pin_base is 0, and supports BOTH edge. WiringX runs well and I have tested interrupt on both kernal.
However, I find another problem:
The example will produce a false interrrupt for the first time. It means that, when there is no signal input, it will print "interrupt\n  timeout\n timeout\n....". So, where does the first "interrupt" come from?

**Comment by CurlyMoo** [comment]
> That's because for Radxa, a OS with kernal vision of 3.0.36 has a pin_base of 160, but wiringX does's considerates this. (Also, 3.0.36 doesn't support edge BOTH). I have fixed this bug.
> For kernal vision 3.18.0, its pin_base is 0, and supports BOTH edge. WiringX runs well and I have tested interrupt on both kernal.

Can you maybe update the radxa code so it will work on both kernel 3.0.36 and 3.18.0? And also create a check that the BOTH edge is not supported on 3.0.36 but is on 3.18.0?

> The example will produce a false interrrupt for the first time. It means that, when there is no signal input, it will print "interrupt\n timeout\n timeout\n....". So, where does the first "interrupt" come from?

Don't know. Can you check if this is fixed when you do this:

```
pinMode(0, OUTPUT);
digitalWrite(0, LOW);
```

So it sets the output pin to low before the interrupt is initialized?

**Comment by ypflll** [comment]
I am still testing modules on RadxaBoard. I'll sort out my code later.
What do you mean by create a check that the BOTH edge is not supported on 3.0.36 but is on 3.18.0?
I have tested on both kernal. BOTH edge works well on 3.18.0. I won't take effort to make BOTH edge work on 3.0.36 cause Raxda will support 4.0 soon, I think.

**Comment by CurlyMoo** [comment]
> What do you mean by create a check that the BOTH edge is not supported on 3.0.36 but is on 3.18.0? I have tested on both kernal.

Users on 3.0.36 should get a warning that the BOTH edge is not supported to prevent complains.

**Comment by ypflll** [comment]
Hi, I've figured it out. 
Why there is a first "interrupt" when no input--it's because in wiringX, you call "x = poll(&polls, 1, ms)" before "(void)read(sysFds[pin], &c, 1)", and you'll get an interrupt for the first time. 
You should call "(void)read(sysFds[pin], &c, 1)" to clear the interrupt before poll.

**Comment by CurlyMoo** [comment]
Ok, i will look into it. The second faulty wiringPi implementation.... I already fixed the first one a while ago.

**Comment by CurlyMoo** [comment]
On a sidenote. I would like to change the LICENSE of wiringX from GPLv3 to MPLv2. Would that be ok by you?

**Comment by shrikantlahase** [comment]
hi @ypflll 
where can i get kernel 3.18 for radxa lite , i want to implement ISR in radxa lite board....?
As you u said previously , kernel 3.0.doesn't support BOTH_EDGE interrupt

Regards,
Shrikant
