### ISSUE TITLE
Hummingboard Keypad

### ISSUE THREAD

**Issue by johnsonjw1** [wiringX/wiringX#3]
Has anyone used wiringX on the Hummingboard to configure a 4x3 keypad without using the breadboard?

If you could point me in the right direction on how to do it using wiringX, that would be very helpful.

**Comment by CurlyMoo** [comment]
What did you try and what issues did you have while doing it?

**Comment by johnsonjw1** [comment]
I've read the basics of wiringPi, connected the keypad to the GPIO pins according to wiringX for my COL(1,4,5,6) and ROW (0,2,3). Downloaded wiringX to Debian Jessie and tried a couple very basic but failed attempts of writing my first few lines of c.  All ID10T errors, I am sure.

Any suggestions or examples that I could take a look at that would help me along? There are plenty of examples and tutorials for the RPi.GPIO and wiringPi with Python, but not much for wiringX in C.

I'm a beginner but willing to learn.

**Comment by CurlyMoo** [comment]
wiringX uses the same logic as wiringPi. Just replace the wiringPi names with wiringX (e.g. `wiringPiSetup -> wiringXSetup`). Also check the pin numbering on `http://wiringx.org`

**Comment by HonesDefwig** [comment]
Love the new addition of the Python module.

Do you have any plan to add Wiringpi's "pullUpDnControl" to WiringX? That is essential for all the keypad tutorials I have come across.

**Comment by CurlyMoo** [comment]
Don't know what it does :)

**Comment by rabeeh** [comment]
To control pull ups and pull downs of the i.MX6 pads for example.
i.MX6 can be configured that each of it's pads can be 22k/47k/100k ohm pulled up, or 100kohm pulled down.
It can be configured with hysteresis on/off, open drain, drive strength and other goodies :)

**Comment by HonesDefwig** [comment]
Right, it's sets the internal pull-up or pull-down resistor mode on the given pin.

http://wiringpi.com/reference/core-functions/

**Comment by CurlyMoo** [comment]
So @rabeeh, nice one for you to implement :+1: Then i will check Raspberry.
