### ISSUE TITLE
make install for libwiringx

### ISSUE THREAD

**Issue by Quark-X10** [wiringX/wiringX#48]
At the moment it is impossible to "make install" and turn on the +x bit for libwiringX, this problem may be solved by replacing FILES by LIBRARY when calling install() for the libs in CMakeFiles.txt:100 (I'm not a CMake expert).

**Comment by CurlyMoo** [comment]
What platform are we talking about?

**Comment by Quark-X10** [comment]
Oh sorry, I'm using Linux. I have tried with cmake 2.8 and 3.2

**Comment by Quark-X10** [comment]
I'm doing tests on my debian laptop and on my gentoo HB and the behaviour is the same

**Comment by CurlyMoo** [comment]
If you follow the installation steps you can just install the final deb or rpm.

**Comment by Quark-X10** [comment]
Yeah i could, but I use gentoo on my HB so I don't want to make an extra dependency on dpkg and cpack where a simple "make install" can do the work.

**Comment by CurlyMoo** [comment]
What files would need the executable bit?

**Comment by Quark-X10** [comment]
the two libraries generated : libwiringX.so and libwringX.a

**Comment by CurlyMoo** [comment]
Why do you want to `execute` them?

**Comment by Quark-X10** [comment]
Oh ! Sorry i had a missing file problem with libwiringX.so when launching my program (which used the lib) and tought the problem was the missing +x but it got fixed. Sorry for your time
