### ISSUE TITLE
Error when installing python gpio

### ISSUE THREAD

**Issue by stefaanbolle** [wiringX/wiringX#5]
I get below error when I try to install the python libraries:

user@server:/opt/wiringX/python# python setup.py install
running install
running build
running build_py
running build_ext
building 'wiringX.gpio' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I../ -I/usr/include/python2.7 -c wiringX/wiringx.c -o build/temp.linux-armv7l-2.7/wiringX/wiringx.o -Wformat=0
wiringX/wiringx.c:34:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'gcc' failed with exit status 1

The file Python.h is not present in the directory structure.

**Comment by CurlyMoo** [comment]
You already asked this question one hour ago:
https://github.com/pilight/wiringX/issues/4
