### ISSUE TITLE
Disable "running on"

### ISSUE THREAD

**Issue by icaruseffect** [wiringX/wiringX#56]
Hi,

Use Case: I am running using wiringX to interface a DHT11 on a bananapi using this [fork](https://github.com/icaruseffect/Adafruit_Python_DHT) and logging to monit using the [munin-dht](https://github.com/agx/munin-dht) plugin

Problem: Every time i call the library from munin-dht to read a value, I get  "running on bananapi" as first result.  This is invoked in src/wiringX.c line 700 with :

> wiringXLog(LOG_DEBUG, "running on a %s", platform->name);
> This results in monit not eating the output, because of the 

Question: Is it possible, to add a toggle for a debug-mode and wrap output which is not relevant outside development in it?

**Comment by CurlyMoo** [comment]
You can also overwrite the logprintf function.

**Comment by icaruseffect** [comment]
For now I just commented it out.  Your idea seems to be more elegant. 
Is there a switch accessible from the python library to alter the behavior of debugging messages?
