### ISSUE TITLE
Segmentation fault(core dump)

### ISSUE THREAD

**Issue by elron27** [wiringX/wiringX#59]
Hi,
I am using a Hummingboard Pro on Arch Linux. I installed your wiringX Package for controlling the I2C bus. Unfortunately it runs about 2 minutes without an error, but then suddenly the python program stops and shows the error message Segmentation fault (core dumped). I googled that fault and it has to do with some register writing which is not allowed, but I am not familiar with the language C. It says that some library written in C used by python comes to an error and stops the program . However, I solved the problem with using the smbus library in python, but I am writing you just for informing you about my experience. Maybe it is useful for you, but if not, I don’t mind. 
Have a nice day.
Greets Elron27

**Comment by CurlyMoo** [comment]
Can you post a debug log of when the error occured with a python debugger?
