### ISSUE TITLE
A10-OLinuXino-LIME support problem

### ISSUE THREAD

**Issue by ajvuik** [wiringX/wiringX#72]
Hello all,
I am currently working on support for the A10-OlinuXino platform from Olimex. It is almost complete, but during testing I came across a problem. I need to manually export and set the direction of a pin for WiringX to work.
I'll try do dive into the problem a bit deeper, but, perhaps someone here can give me some pointers on where to look for.

I'm not getting any error messages, or anything. Just the IO won't go on or off if I don't set the direction manualy in bash.

**Comment by CurlyMoo** [comment]
Did you already put the code online in your fork?

**Comment by ajvuik** [comment]
Yes, it's on-line in my fork.

**Comment by CurlyMoo** [comment]
And where is that so we don't have so search for it ourselves.

**Comment by ajvuik** [comment]
In /src/platform/Olimex are the files that I added. It uses the Allwinner A10 SOC. 
I also added this directory in the CMakeLists.txt so it will be included when building WiringX.
WiringX.c had been modified to add the .h file and init the platform.

**Comment by CurlyMoo** [comment]
Where is your fork?

**Comment by ajvuik** [comment]
https://github.com/ajvuik/wiringX

**Comment by CurlyMoo** [comment]
How do you know you created the right map when wiringx-blink doesn't work?

**Comment by ajvuik** [comment]
You mean the GPIO map?
Because when I export and set the direction manually and I run the blink program, it works.(as in the correct LED blinks)

... on hinsight, there is 1 zero to much at the start. This was to try if I made a mistake with the mapping, but as far as I can see, there isn't. So the 1st mapping can be omitted.

**Comment by CurlyMoo** [comment]
You can't rely on the userspace numbers. You need to map the pins by (bulk) trying the memory areas from the A10 module.

**Comment by ajvuik** [comment]
No, I cross reference the userspace with the memory mapping to check if I have the right GPIO. I don't rely on it for WiringX

What I did is: I used the BananaPi 1 platform files and used them as a template for the new platform files.

**Comment by CurlyMoo** [comment]
That what i said, the memory map number can be totally different from the userspace number. That's why the solidrun platforms have a separate gpio map and a irq map.
