### ISSUE TITLE
Python ImportError in Hummingboard

### ISSUE THREAD

**Issue by David-Proconsi** [wiringX/wiringX#99]
```python
from wiringX import gpio
```
>ImportError: /usr/local/lib/python2.7/dist-packages/wiringX/gpio.so: undefined symbol: raspberrypizeroInit

I solved it adding in python/setup.py

```
'../src/platform/raspberrypi/raspberrypizero.c',
```

Like that:

```
'../src/platform/raspberrypi/raspberrypi2.c',
'../src/platform/raspberrypi/raspberrypi3.c',
'../src/platform/raspberrypi/raspberrypizero.c',
'../src/platform/solidrun/hummingboard_base_pro_dq.c',
'../src/platform/solidrun/hummingboard_base_pro_sdl.c',
```

Then compile and reinstall.

I think there are more missing references to raspberrypizero

**Comment by CurlyMoo** [comment]
Can you do a PR with your findings?

**Comment by David-Proconsi** [comment]
I tried but...

![imagen](https://cloud.githubusercontent.com/assets/18136479/25938902/469f588a-3631-11e7-9e76-c09d74bb6601.png)

**Comment by pilino1234** [comment]
You need to fork the pilight repo to your own Github account first, push the changes there, and then make a PR. See https://guides.github.com/activities/forking/

**Comment by David-Proconsi** [comment]
Thanks, I use git everyday but this is the first time I collaborating in a public project.
#100
